---
# tasks file for role_java

- name: Install Java Setup from repository
  ansible.builtin.import_tasks: install-repo.yml
  when:
    - java_setup == 'repo'

- name: Install Java Setup from binary archive
  ansible.builtin.include_tasks: install-binary.yml
  when:
    - java_setup == 'binary'
  with_items: "{{ java_versions }}"
  loop_control:
    loop_var: java
